version: '1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kotlin-rag:latest
    container_name: kotlin-rag
    depends_on:
      - chromadb
      - ollama
    ports:
      - "8080:8080"
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434

  chromadb:
    image: 'chromadb/chroma:latest'
    container_name: chroma
    ports:
      - "8000:8000"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-local:/root/.ollama
    command:  serve &&
              run llama3 &&
              pull mxbai-embed-large &&
              pull llama3.1


volumes:
  ollama-local: